name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          npm install -g bats
          echo "Secret is ${{ secrets.SUPER_SECRET }}"
          echo "Oops. We just leaked a secret. 🤦‍♂️"
          bats -v
